services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ch-assignment
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
